# Generated by Django 5.2.9 on 2025-12-23 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mqtt_broker', models.CharField(default='localhost', max_length=255)),
                ('mqtt_port', models.IntegerField(default=1883)),
                ('mqtt_username', models.CharField(blank=True, max_length=255)),
                ('mqtt_password', models.CharField(blank=True, max_length=255)),
                ('mqtt_topic_prefix', models.CharField(default='meshcore', max_length=255)),
                ('serial_port', models.CharField(default='/dev/ttyACM0', max_length=255)),
                ('serial_baud', models.IntegerField(default=115200)),
                ('auto_acknowledge', models.BooleanField(default=True)),
                ('store_packets', models.BooleanField(default=True)),
                ('forward_to_mqtt', models.BooleanField(default=True)),
                ('ignored_node_types', models.JSONField(default=list, help_text='List of node types to ignore')),
                ('allowed_channels', models.JSONField(default=list, help_text='List of channel hashes to allow (empty = all)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bridge Configuration',
                'verbose_name_plural': 'Bridge Configurations',
            },
        ),
        migrations.CreateModel(
            name='BridgeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error')], default='stopped', max_length=20)),
                ('serial_connected', models.BooleanField(default=False)),
                ('mqtt_connected', models.BooleanField(default=False)),
                ('messages_received', models.BigIntegerField(default=0)),
                ('messages_published', models.BigIntegerField(default=0)),
                ('packets_processed', models.BigIntegerField(default=0)),
                ('errors', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bridge Status',
                'verbose_name_plural': 'Bridge Status',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_hash', models.CharField(db_index=True, help_text='First byte of SHA256(shared_key)', max_length=2, unique=True)),
                ('shared_key', models.BinaryField(help_text='Shared encryption key for channel', max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.BinaryField(db_index=True, help_text='Ed25519 public key', max_length=32, unique=True)),
                ('node_hash', models.CharField(db_index=True, help_text='First byte of public key (hex)', max_length=2)),
                ('node_type', models.CharField(choices=[('chat', 'Chat Node'), ('repeater', 'Repeater'), ('room_server', 'Room Server'), ('sensor', 'Sensor'), ('companion', 'Companion')], default='chat', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=4)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_advertisement', models.DateTimeField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_ignored', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['node_hash', 'is_online'], name='meshcore_no_node_ha_4a1a80_idx'), models.Index(fields=['node_type', 'is_online'], name='meshcore_no_node_ty_dff009_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('checksum', models.CharField(db_index=True, help_text='CRC32 checksum', max_length=8)),
                ('sender_hash', models.CharField(db_index=True, max_length=2)),
                ('recipient_hash', models.CharField(blank=True, db_index=True, max_length=2)),
                ('message_type', models.CharField(choices=[('txt_msg', 'Text Message'), ('grp_txt', 'Group Text'), ('req', 'Request'), ('response', 'Response'), ('ack', 'Acknowledgment'), ('anon_req', 'Anonymous Request')], max_length=20)),
                ('txt_type', models.CharField(choices=[('plain', 'Plain Text'), ('cli', 'CLI Command'), ('signed', 'Signed Text')], default='plain', max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('attempt_number', models.IntegerField(default=0)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('snr', models.FloatField(blank=True, null=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='meshcore.channel')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='meshcore.node')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='meshcore.node')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NodeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_mv', models.IntegerField(blank=True, help_text='Battery voltage in millivolts', null=True)),
                ('rssi', models.IntegerField(blank=True, help_text='Last RSSI value', null=True)),
                ('snr', models.FloatField(blank=True, help_text='Last SNR value', null=True)),
                ('packets_received', models.BigIntegerField(default=0)),
                ('packets_sent', models.BigIntegerField(default=0)),
                ('packets_flood_sent', models.BigIntegerField(default=0)),
                ('packets_direct_sent', models.BigIntegerField(default=0)),
                ('packets_flood_received', models.BigIntegerField(default=0)),
                ('packets_direct_received', models.BigIntegerField(default=0)),
                ('duplicate_packets', models.BigIntegerField(default=0)),
                ('tx_queue_length', models.IntegerField(default=0)),
                ('free_queue_length', models.IntegerField(default=0)),
                ('airtime_seconds', models.BigIntegerField(default=0, help_text='Total time transmitting')),
                ('uptime_seconds', models.BigIntegerField(default=0, help_text='Total uptime')),
                ('error_flags', models.IntegerField(default=0)),
                ('collected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='meshcore.node')),
            ],
            options={
                'verbose_name': 'Node Statistics',
                'verbose_name_plural': 'Node Statistics',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(choices=[('flood', 'Flood'), ('direct', 'Direct'), ('transport_flood', 'Transport Flood'), ('transport_direct', 'Transport Direct')], max_length=20)),
                ('payload_type', models.CharField(choices=[('req', 'Request'), ('response', 'Response'), ('txt_msg', 'Text Message'), ('ack', 'Acknowledgment'), ('advert', 'Advertisement'), ('grp_txt', 'Group Text'), ('grp_data', 'Group Data'), ('anon_req', 'Anonymous Request'), ('path', 'Path'), ('trace', 'Trace'), ('multipart', 'Multipart'), ('control', 'Control'), ('raw_custom', 'Raw Custom')], max_length=20)),
                ('payload_version', models.IntegerField(default=1)),
                ('transport_code_1', models.IntegerField(blank=True, null=True)),
                ('transport_code_2', models.IntegerField(blank=True, null=True)),
                ('path', models.JSONField(default=list, help_text='List of node hashes in path')),
                ('hop_count', models.IntegerField(default=0)),
                ('payload_data', models.BinaryField(help_text='Raw payload bytes')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('snr', models.FloatField(blank=True, null=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packets', to='meshcore.message')),
            ],
            options={
                'verbose_name': 'Packet',
                'verbose_name_plural': 'Packets',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender_hash', 'timestamp'], name='meshcore_me_sender__644f62_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient_hash', 'timestamp'], name='meshcore_me_recipie_e25d99_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type', 'timestamp'], name='meshcore_me_message_54da6f_idx'),
        ),
        migrations.AddIndex(
            model_name='nodestats',
            index=models.Index(fields=['node', 'collected_at'], name='meshcore_no_node_id_d88288_idx'),
        ),
        migrations.AddIndex(
            model_name='packet',
            index=models.Index(fields=['payload_type', 'received_at'], name='meshcore_pa_payload_6ab724_idx'),
        ),
        migrations.AddIndex(
            model_name='packet',
            index=models.Index(fields=['route_type', 'received_at'], name='meshcore_pa_route_t_552de5_idx'),
        ),
    ]
