# Generated by Django 5.2.9 on 2025-12-27 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meshcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(db_index=True, help_text='Unique file identifier', max_length=32, unique=True)),
                ('session_id', models.IntegerField(db_index=True, help_text='Multi-part session ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('voice', 'Voice Message'), ('file', 'Generic File')], max_length=10)),
                ('filename', models.CharField(max_length=255)),
                ('original_size', models.IntegerField(help_text='Original file size in bytes')),
                ('compressed_size', models.IntegerField(blank=True, help_text='Compressed size in bytes', null=True)),
                ('channel_hash', models.CharField(blank=True, help_text='For group messages', max_length=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('sending', 'Sending'), ('sent', 'Sent'), ('receiving', 'Receiving'), ('received', 'Received'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Transfer progress percentage')),
                ('total_packets', models.IntegerField(default=0)),
                ('received_packets', models.IntegerField(default=0)),
                ('original_file', models.FileField(blank=True, null=True, upload_to='media/original/')),
                ('compressed_file', models.FileField(blank=True, null=True, upload_to='media/compressed/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (duration, resolution, etc.)')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_media', to='meshcore.node')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_media', to='meshcore.node')),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='meshcore.node')),
                ('media_files', models.ManyToManyField(blank=True, related_name='galleries', to='meshcore.mediafile')),
            ],
            options={
                'verbose_name': 'Media Gallery',
                'verbose_name_plural': 'Media Galleries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultiPartPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet_index', models.IntegerField(help_text='Packet sequence number')),
                ('data', models.BinaryField(help_text='Packet data chunk')),
                ('size', models.IntegerField(help_text='Size of this chunk in bytes')),
                ('sent', models.BooleanField(default=False)),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('ack_at', models.DateTimeField(blank=True, null=True)),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='meshcore.mediafile')),
            ],
            options={
                'verbose_name': 'Multi-Part Packet',
                'verbose_name_plural': 'Multi-Part Packets',
                'ordering': ['packet_index'],
            },
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['session_id', 'status'], name='meshcore_me_session_aab6c7_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['sender', 'created_at'], name='meshcore_me_sender__d688f9_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['media_type', 'status'], name='meshcore_me_media_t_a32ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='multipartpacket',
            index=models.Index(fields=['media_file', 'packet_index'], name='meshcore_mu_media_f_5bd5c2_idx'),
        ),
        migrations.AddIndex(
            model_name='multipartpacket',
            index=models.Index(fields=['sent', 'acknowledged'], name='meshcore_mu_sent_5aae69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='multipartpacket',
            unique_together={('media_file', 'packet_index')},
        ),
    ]
